#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[198] =
    {   0,
        0,    0,    0,    0,   49,   46,   10,    9,   46,   46,
        8,   46,    6,    5,   46,   46,   46,   46,   46,   46,
       46,   46,   46,    7,   16,   48,   46,   43,   41,   40,
       46,   42,   46,    0,   45,   44,   43,   41,   40,   46,
       42,   46,   21,   46,    4,    3,    1,   32,   32,   31,
       27,   25,   26,   28,   29,   30,   32,   46,    0,   43,
       41,   40,   46,   19,   42,   20,   46,   46,   46,   46,
       46,   46,   46,   46,   16,   16,   16,   16,   16,   16,
       37,   35,   36,   39,   44,   37,   35,   36,   39,   46,
        0,   43,   17,   41,   40,   46,   42,   46,    0,   43,

       41,   40,   46,   42,   18,    2,   19,   37,   35,   36,
       39,   46,   46,   46,   46,   46,   46,   46,   46,   16,
       16,   16,   16,   16,   17,   37,   35,   36,   39,   18,
       37,   35,   36,   39,   18,   18,   18,   18,   18,   18,
       18,   18,   11,   46,   46,   46,   46,   46,   46,   46,
       18,   18,   18,   18,   18,   18,   46,   33,   46,   46,
       46,   46,   46,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   24,   46,   13,   15,   46,   34,   18,
       18,   18,   18,   18,   18,   18,   23,   46,   46,   18,
       39,   12,   14,   38,   22,   38,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    7,    1,    8,
        9,    1,    1,    1,    1,    1,    1,   10,   10,   11,
       10,   10,   10,   10,   10,   10,   10,    1,    1,   12,
        1,   13,    1,    1,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        1,   14,    1,    1,   10,   15,   10,   10,   16,   17,

       18,   10,   10,   10,   19,   10,   20,   21,   10,   22,
       23,   24,   10,   25,   26,   27,   28,   29,   10,   30,
       10,   10,   31,   32,   33,   34,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[35] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[215] =
    {   0,
        0,    0,    0,    0,  373,   28,  702,  702,   59,   91,
      702,   36,  702,   31,  124,  155,  181,  207,  233,  259,
      285,  311,   29,  702,   62,  702,   35,  702,  702,  702,
      120,  702,  342,   34,  702,   36,   62,   74,   75,   74,
       79,  373,   62,  404,  702,  702,  363,   67,  702,  702,
      702,  702,  702,  128,  121,  125,  702,  436,  336,  335,
      327,  326,  159,  127,  317,  131,  156,  158,  159,  166,
      173,  174,  181,  183,  196,    0,    0,    0,  210,    0,
      702,  702,  702,  218,  702,  150,  158,  213,  222,  467,
      319,  312,    0,  311,  310,  242,  304,  498,  279,  278,

      270,  269,  245,  250,  530,  702,  702,  259,  249,  248,
      255,  252,  258,  270,  264,  215,  271,  225,  267,    0,
        0,    0,    0,  294,  252,  251,  242,  235,  302,  235,
      194,  193,  182,  323,  561,  206,  174,  180,  177,  158,
      326,  141,  282,  334,  346,  304,  343,  346,  345,  353,
      159,  592,  124,  123,   89,  376,  387,  702,  361,  373,
      374,  375,  396,   50,  624,  271,   58,  389,  398,  401,
      413,  408,    0,  440,  437,  406,  412,  439,  702,  452,
       49,    0,  409,  440,  457,  475,  484,  484,  485,  459,
      508,  452,  483,  521,  534,  538,  702,  657,   45,  661,

      665,  669,   44,  673,  677,  681,  683,   35,  687,  691,
      693,  695,  697,  699
    } ;

static const flex_int16_t yy_def[215] =
    {   0,
      197,    1,  198,  198,  197,  199,  197,  197,  200,  197,
      197,  199,  197,  197,  201,  202,  199,  199,  199,  199,
      199,  199,   22,  197,  203,  197,   22,  197,  197,  197,
      199,  197,  200,  204,  197,   22,  204,  204,  204,   33,
      204,  205,   10,  206,  197,  197,  197,   22,  197,  197,
      197,  197,  197,  199,   22,   22,  197,  202,  207,  207,
      207,  207,   58,   22,  207,   22,   22,   22,   22,   22,
       22,   22,   22,   22,  203,  208,  208,  208,  203,  208,
      197,  197,  197,  199,  197,  204,  204,  204,   33,  205,
      209,  209,   90,  209,  209,   90,  209,  206,  210,  210,

      210,  210,   98,  210,  211,  197,  197,  207,  207,  207,
       58,   22,   22,   22,   22,   22,   22,   22,   22,  208,
      208,  208,  208,  203,  209,  209,  209,  209,   90,  212,
      210,  210,  210,   98,  211,  212,  135,  212,  212,  212,
      135,  212,   22,   22,  199,   22,   22,   22,   22,   22,
      212,  213,  212,  212,  212,  135,  199,  197,   22,   22,
       22,   22,  199,  214,  213,  214,  165,  214,  214,  214,
      165,  214,  135,  199,   22,   22,   22,   22,  197,  214,
      212,  165,  214,  214,  214,  165,  199,   22,   22,  214,
      199,   22,   22,  199,  199,  199,    0,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197
    } ;

static const flex_int16_t yy_nxt[737] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,    6,    6,
       12,   13,   14,   15,   16,   17,    6,   18,    6,   19,
       20,    6,    6,   21,    6,   22,    6,   23,    6,    6,
        6,   24,    6,   25,   28,  120,   35,   46,   85,   29,
       30,   31,   28,   47,   75,   27,   27,   29,   45,   31,
       73,   27,   27,   27,  151,  180,   74,   27,   27,   32,
       34,   35,   34,   36,   35,   37,   85,   32,   76,   27,
       38,   39,   40,   77,   78,   79,   35,   35,   85,   85,
       86,   35,  181,   85,   27,   87,   88,   89,  182,   27,
       41,   27,   27,   80,  151,   27,   27,   28,   42,   27,

       43,   43,   29,   30,   31,   27,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   44,   32,   27,   27,   49,   81,   50,  151,  151,
       51,   82,   83,   84,   81,   52,   53,   54,   27,   82,
       83,   84,   27,   27,   27,   55,  151,   27,   27,   27,
       56,   32,   35,   27,   85,   57,   59,   59,   59,   32,
       35,   60,   85,  151,  151,  108,   61,   62,   63,   64,
      109,  110,  111,   27,  112,   27,   27,  113,   27,  114,
       27,   27,  151,   27,  115,  151,   65,   28,   27,  164,
       27,   27,   29,   30,   31,   27,   27,   66,   27,  116,

       27,  117,   76,   27,  152,   27,  118,   77,   78,   79,
      119,  151,   32,   28,  130,   35,  121,   85,   29,   30,
       31,  122,  123,  124,   81,  130,  130,   80,   86,   82,
       83,   84,  147,   87,   88,   89,   67,   27,   32,   28,
      151,   80,  149,  125,   29,   30,   31,   27,  126,   32,
      125,  131,   68,  127,  128,  129,  132,  133,  134,  125,
      125,  108,  107,  107,   32,   28,  109,  110,  111,   27,
       29,   30,   31,  107,   27,   27,  180,  144,  143,   69,
       27,   27,  130,  145,   27,  146,   27,   27,   27,   27,
       32,   28,   27,   27,  150,  148,   29,   30,   31,   27,

      121,  130,  130,  181,   27,  122,  123,  124,  126,   70,
      130,  130,  125,  127,  128,  129,   32,   28,  125,  125,
      125,   27,   29,   30,   31,   80,   27,  125,   71,  131,
      159,  107,  153,   72,  132,  133,  134,  154,  155,  156,
      107,  107,   32,   34,   35,   34,   36,  157,   37,  107,
      107,   27,   81,   38,   39,   40,   27,  158,   83,   84,
       27,  161,   27,   27,  160,   27,  163,   27,   27,  106,
       27,  162,  197,   41,   91,   27,   91,   32,  175,   92,
      197,   93,  153,   27,   94,   95,   96,  154,  155,  156,
       27,  177,  178,   81,  180,   27,   27,   27,   82,   83,

      174,  176,  179,  180,   97,   99,  180,   82,   83,   84,
      100,  197,  197,  180,  180,  101,  102,  103,   32,  183,
      197,  181,  197,   27,  184,  185,  186,   32,   27,   27,
      181,  197,  197,  181,   27,  104,  105,   59,   59,   59,
      181,  181,   60,  197,  197,  180,   81,   61,   62,   63,
       64,   82,   83,  187,   27,  197,   27,  180,  188,   27,
      189,   27,  180,  197,  180,  197,  197,   65,   91,   27,
       91,   32,  181,   92,   27,   93,  197,  197,   94,   95,
       96,  183,  190,  197,  181,  197,  184,  185,  186,  181,
       81,  181,  197,  197,  197,   82,   83,  191,   97,   99,

       27,   27,   27,  197,  100,   27,   27,   27,  197,  101,
      102,  103,  192,  193,   81,   32,  197,  197,  197,   82,
       83,  194,  197,  197,  197,  197,  197,   81,  197,  104,
      105,  136,   82,   83,  195,  137,  138,  197,  197,   32,
       81,  139,  140,  141,   81,   82,   83,  196,  197,   82,
       83,  196,   32,  197,  197,  197,  197,  197,  197,  197,
      197,  142,  136,  197,  197,   32,  137,  138,  197,   32,
      197,  197,  139,  140,  141,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  142,  166,  197,  197,  197,  167,  168,  197,

      197,  197,  197,  169,  170,  171,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  172,  173,  166,  197,  197,  197,  167,
      168,  197,  197,  197,  197,  169,  170,  171,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  172,  173,   26,   26,   26,
       26,   33,   33,   33,   33,   48,   48,  197,   48,   58,
       58,   58,   58,   34,   34,   34,   34,   90,   90,  197,
       90,   98,   98,   59,   59,   59,   59,   91,   91,  197,
       91,   99,   99,  135,  135,  136,  136,  165,  165,  166,

      166,    5,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197
    } ;

static const flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,  208,   34,   14,   34,    6,
        6,    6,   12,   14,  203,  199,   23,   12,   12,   12,
       23,   23,   27,   36,  181,  164,   23,   27,   36,    6,
        9,    9,    9,    9,   37,    9,   37,   12,   25,   43,
        9,    9,    9,   25,   25,   25,   38,   39,   38,   39,
       40,   41,  164,   41,   48,   40,   40,   40,  167,   48,
        9,   10,   43,   25,  155,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   15,   31,   15,  154,  153,
       15,   31,   31,   31,   54,   15,   15,   15,   55,   54,
       54,   54,   56,   55,   64,   15,  142,   56,   66,   64,
       15,   31,   86,   66,   86,   15,   16,   16,   16,   54,
       87,   16,   87,  140,  151,   63,   16,   16,   16,   16,
       63,   63,   63,   67,   67,   68,   69,   68,   67,   69,
       68,   69,  139,   70,   70,  138,   16,   17,   70,  151,
       71,   72,   17,   17,   17,   71,   72,   17,   73,   71,

       74,   72,   75,   73,  137,   74,   73,   75,   75,   75,
       74,  136,   17,   18,  133,   88,   79,   88,   18,   18,
       18,   79,   79,   79,   84,  132,  131,   75,   89,   84,
       84,   84,  116,   89,   89,   89,   18,  116,   18,   19,
      130,   79,  118,  128,   19,   19,   19,  118,   96,   84,
      127,  103,   19,   96,   96,   96,  103,  103,  103,  126,
      125,  111,  110,  109,   19,   20,  111,  111,  111,  112,
       20,   20,   20,  108,  112,  113,  166,  113,  112,   20,
      113,  115,  104,  114,  119,  115,  115,  114,  117,  119,
       20,   21,  114,  117,  119,  117,   21,   21,   21,  143,

      124,  102,  101,  166,  143,  124,  124,  124,  129,   21,
      100,   99,   97,  129,  129,  129,   21,   22,   95,   94,
       92,  146,   22,   22,   22,  124,  146,   91,   22,  134,
      146,   65,  141,   22,  134,  134,  134,  141,  141,  141,
       62,   61,   22,   33,   33,   33,   33,  144,   33,   60,
       59,  144,  145,   33,   33,   33,  144,  145,  145,  145,
      147,  148,  149,  148,  147,  147,  150,  149,  148,   47,
      150,  149,    5,   33,   42,  150,   42,  145,  159,   42,
        0,   42,  156,  159,   42,   42,   42,  156,  156,  156,
      160,  161,  162,  157,  168,  160,  161,  162,  157,  157,

      157,  160,  163,  169,   42,   44,  170,  163,  163,  163,
       44,    0,    0,  172,  183,   44,   44,   44,  157,  171,
        0,  168,    0,  176,  171,  171,  171,  163,  176,  177,
      169,    0,    0,  170,  177,   44,   44,   58,   58,   58,
      172,  183,   58,    0,    0,  184,  174,   58,   58,   58,
       58,  174,  174,  174,  175,    0,  178,  180,  175,  175,
      178,  178,  185,    0,  190,    0,    0,   58,   90,  192,
       90,  174,  184,   90,  192,   90,    0,    0,   90,   90,
       90,  186,  180,    0,  180,    0,  186,  186,  186,  185,
      187,  190,    0,    0,    0,  187,  187,  187,   90,   98,

      193,  188,  189,    0,   98,  193,  188,  189,    0,   98,
       98,   98,  188,  189,  191,  187,    0,    0,    0,  191,
      191,  191,    0,    0,    0,    0,    0,  194,    0,   98,
       98,  105,  194,  194,  194,  105,  105,    0,    0,  191,
      195,  105,  105,  105,  196,  195,  195,  195,    0,  196,
      196,  196,  194,    0,    0,    0,    0,    0,    0,    0,
        0,  105,  135,    0,    0,  195,  135,  135,    0,  196,
        0,    0,  135,  135,  135,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  135,  152,    0,    0,    0,  152,  152,    0,

        0,    0,    0,  152,  152,  152,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  152,  152,  165,    0,    0,    0,  165,
      165,    0,    0,    0,    0,  165,  165,  165,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  165,  165,  198,  198,  198,
      198,  200,  200,  200,  200,  201,  201,    0,  201,  202,
      202,  202,  202,  204,  204,  204,  204,  205,  205,    0,
      205,  206,  206,  207,  207,  207,  207,  209,  209,    0,
      209,  210,  210,  211,  211,  212,  212,  213,  213,  214,

      214,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[49] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 9 "shell.l"
#include <cstring>
#include <stack>
#include "y.tab.hh"
#include <unistd.h>     // For pipe(), dup2(), etc.
#include <sys/types.h>  // For pid_t
#include <sys/wait.h>   // For waitpid()
#include <stdlib.h>     // For system()
#include <fcntl.h>      // For open(), etc.
#include <string.h>

extern "C" char * read_line();

int mygetc(FILE * f) {
  static char *p;
  char ch;

  if (!isatty(0)) {
    // stdin is not a tty. Call real getc
    return getc(f);
  }

  // stdin is a tty. Call our read_line.
  if (p==NULL || *p == 0) {
    char * s = read_line();
    p = s;
  }

  ch = *p;
  p++;

  return ch;
}

#undef getc
#define getc(f) mygetc(f)


int return_code = 0;      // For ${?}
pid_t pid_last = 0;       // For ${!}
std::string arg_last; // For ${_}


// For handling source command with multiple input buffers
struct Input {
    YY_BUFFER_STATE buffer;
    FILE *file;
    char *filename;
};

std::stack<Input> input_stack;

void source_file(const char *filename) {
    FILE *file = fopen(filename, "r");
    if (!file) {
        perror("source");
        return;
    }
    
    // Save the current input
    Input input;
    input.buffer = YY_CURRENT_BUFFER;
    input.file = file;
    input.filename = strdup(filename);
    
    input_stack.push(input);
    
    // Switch to the new file
    yy_switch_to_buffer(yy_create_buffer(file, YY_BUF_SIZE));
}

static void yyunput(int c, char *buf_ptr);
void myunputc(int c) {
  unput(c);
}
#line 788 "lex.yy.cc"

#line 790 "lex.yy.cc"

#define INITIAL 0
#define string_condition 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 86 "shell.l"


#line 1011 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 198 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 702 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "shell.l"
{
  return GREATGREAT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "shell.l"
{
  return GREATGREATAMPERSAND;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "shell.l"
{
  return GREATAMPERSAND;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "shell.l"
{
  return TWOGREAT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "shell.l"
{
  return PIPE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "shell.l"
{
  return AMPERSAND;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 112 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 118 "shell.l"
{
  return EXIT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 "shell.l"
{
  return PRINTENV;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "shell.l"
{
  return SETENV;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "shell.l"
{
  return UNSETENV;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 130 "shell.l"
{
  return SOURCE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "shell.l"
{
  // Tilde Expansion
  std::string str = std::string(yytext);
  std::string home_dir = getenv("HOME");
  if (str.size() != 1) { // Checks if it is a single ~
    if (str[1] == '/') {
      // Checks if it is a path
      str = home_dir + str.substr(1);
    }
    else {
      // Else it is a username
      str = std::string("/homes/") + str.substr(1,-1);
    }
    yylval.cpp_string = new std::string(str);
  }
  else{
    yylval.cpp_string = new std::string(home_dir);
  }
  return WORD;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "shell.l"
{
  //subshell

  std::string str = yytext;
  //remove $ 
  if (str.at(0) == '$') {
      str = str.substr(1,str.size()-1);
  }
  str = str.substr(1,str.size()-2);
  //remove paren
  std::size_t index = str.find(")");
  std::string temp_string = str.substr(0,index-2);

  char *subshell = const_cast<char*> (temp_string.c_str());
  int defaultin = dup(0);
  int defaultout = dup(1);
  //pipe
  int fdpipein[2];
  pipe(fdpipein);
  int fdpipeout[2];
  pipe(fdpipeout);

  write(fdpipein[1], subshell, strlen(subshell));
  write(fdpipein[1], "\n", 1);
  close(fdpipein[1]);

  dup2(fdpipein[0], 0);
  close(fdpipein[0]);
  dup2(fdpipeout[1], 1);
  close(fdpipeout[1]);
  
  int ret = fork();
  if (ret == 0) {
    char ** null_ptr = NULL;
    execvp("/proc/self/exe", null_ptr);
    _exit(1);
  } 
  else if (ret < 0) {
    perror("fork");
    exit(1);
  }
  dup2(defaultin, 0);
  dup2(defaultout, 1);
  close(defaultin);
  close(defaultout);

  char c;
  char * buffer = (char *) malloc (4096);
  int i = 0;
  //transfer data to buffer
  while (read(fdpipeout[0], &c, 1)) {
    if (c == '\n') {
      buffer[i++] = ' ';
    }
    else{
      buffer [i++] = c;
    }
  }
  buffer[i] = '\0';

  int j = i - 1;
  for (j = i - 1; j >= 0; j--) {
    myunputc(buffer[j]);
  }
  close(fdpipeout[0]);

}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 223 "shell.l"
{
  // Variable Expansion
  std::string variable = yytext;
  // Nested and simple variables with curly braces
  std::string result = "";
  if (variable.find("${") <= variable.size()){
    while(variable.find("${") <= variable.size()){
      std::string left_substring= variable.substr(0,variable.find("${"));
      result += left_substring;
      std::string right_substring = variable.substr(variable.find("}")+strlen("}"));
      std::string main = variable.substr(left_substring.size()+strlen("${"),variable.find("}")-variable.find("${")-2);
      // Special Cases
      if(main.compare("$") == 0){
        result += std::to_string(getpid());
      }
      else if(main.compare("?") == 0){
        result += std::to_string(return_code);
      }
      else if(main.compare("!") == 0){
        result += std::to_string(pid_last);
      }
      else if(main.compare("_") == 0){
        result += arg_last;
      }
      else if(main.compare("SHELL") == 0){
        char real_path[2048];
        result += realpath("/proc/self/exe",real_path);

      }
      else{
        char * temp = getenv(main.c_str());
        if(!temp) {
          result += main.c_str();
        }else{
          result += temp;
        }
      }
      variable = right_substring;
    }
    result += variable;
  }
  else{
    result += variable;
  }
  yylval.cpp_string = new std::string(result);
  return WORD;
}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 271 "shell.l"
{
  // Extract the command inside backticks - skip the backticks
  std::string cmdStr = yytext;
  cmdStr = cmdStr.substr(1, cmdStr.length() - 2); // Remove backticks
  
  const char* command = cmdStr.c_str();
  
  // Save default input/output
  int defaultin = dup(0);
  int defaultout = dup(1);
  
  // Create pipes
  int fdpipein[2];
  int fdpipeout[2];
  
  if (pipe(fdpipein) < 0 || pipe(fdpipeout) < 0) {
    perror("pipe");
    return NOTOKEN;
  }
  
  // Write command to input pipe
  write(fdpipein[1], command, strlen(command));
  write(fdpipein[1], "\n", 1);
  write(fdpipein[1], "exit\n", 5); // Make sure the subshell exits
  close(fdpipein[1]);
  
  // Set up redirections
  dup2(fdpipein[0], 0);  // Connect pipe to stdin
  close(fdpipein[0]);
  dup2(fdpipeout[1], 1); // Connect pipe to stdout
  close(fdpipeout[1]);
  
  // Fork and exec
  pid_t pid = fork();
  
  if (pid == 0) {
    // Child process
    execl("/proc/self/exe", "shell", NULL);
    perror("execl");
    _exit(1);
  } 
  else if (pid < 0) {
    perror("fork");
    return NOTOKEN;
  }
  
  // Restore default input/output
  dup2(defaultin, 0);
  dup2(defaultout, 1);
  close(defaultin);
  close(defaultout);
  
  // Read output from the pipe
  char buffer[4096];
  int index = 0;
  char c;
  
  // Read character by character
  while (read(fdpipeout[0], &c, 1) > 0 && index < 4095) {
    if (c == '\n') {
      buffer[index++] = ' '; // Replace newlines with spaces
    } else {
      buffer[index++] = c;
    }
  }
  
  buffer[index] = '\0';
  close(fdpipeout[0]);
  
  // Wait for child to complete
  waitpid(pid, NULL, 0);
  
  // Push the characters back into the input stream in reverse order
  for (int i = index - 1; i >= 0; i--) {
    myunputc(buffer[i]);
  }
  
  return NOTOKEN;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string_condition):
#line 351 "shell.l"
{
    if (input_stack.empty()) {
        return 0;  // End of main input
    } else {
        Input input = input_stack.top();
        input_stack.pop();
        
        yy_delete_buffer(YY_CURRENT_BUFFER);
        fclose(input.file);
        free(input.filename);
        
        yy_switch_to_buffer(input.buffer);
    }
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 365 "shell.l"
{
  return CD;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 368 "shell.l"
{
  // Simple variables without curly braces
  // Remove $ to get the variable name
  char var_name[256];
  strncpy(var_name, yytext + 1, strlen(yytext) - 1);
  var_name[strlen(yytext) - 1] = '\0';
  
  // Get the environment variable value
  const char *value = getenv(var_name);
  
  // If the variable exists, return its value, otherwise return empty string
  if (value) {
    yylval.cpp_string = new std::string(value);
  } else {
    yylval.cpp_string = new std::string("");
  }
  
  return WORD;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 387 "shell.l"
{
  /* 6 literal backslashes */
  yylval.cpp_string = new std::string("kkkk\\");
  return WORD;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 392 "shell.l"
{
  yylval.cpp_string = new std::string("kkkk\\");
  return WORD;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 396 "shell.l"
{
  yylval.cpp_string = new std::string("kkkk\\");
  return WORD;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 400 "shell.l"
{
  yylval.cpp_string = new std::string("<");
  return WORD;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 404 "shell.l"
{
  yylval.cpp_string = new std::string(">");
  return WORD;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 408 "shell.l"
{
  yylval.cpp_string = new std::string("&");
  return WORD;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 412 "shell.l"
{
  yylval.cpp_string = new std::string("\\");
  return WORD;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 416 "shell.l"
{
  yylval.cpp_string = new std::string("\n");
  return WORD;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 420 "shell.l"
{
  yylval.cpp_string = new std::string("\t");
  return WORD;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 424 "shell.l"
{
  yylval.cpp_string = new std::string(" ");
  return WORD;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 428 "shell.l"
{
  char buffer[2];
  buffer[0] = yytext[1];
  buffer[1] = '\0';
  yylval.cpp_string = new std::string(buffer);
  return WORD;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 435 "shell.l"
{
  yylval.cpp_string = new std::string("lll<");
  return WORD;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 439 "shell.l"
{
  yylval.cpp_string = new std::string("uuuu&");
  return WORD;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 443 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-2] = '\0';
  std::string *result = new std::string(yytext);
  result->append("<");
  yylval.cpp_string = result;
  return WORD;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 451 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-2] = '\0';
  std::string *result = new std::string(yytext);
  result->append(">");
  yylval.cpp_string = result;
  return WORD;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 459 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-2] = '\0';
  std::string *result = new std::string(yytext);
  result->append("&");
  yylval.cpp_string = result;
  return WORD;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 467 "shell.l"
{
  /* Match kkkk followed by 4 or more backslashes */
  yylval.cpp_string = new std::string("kkkk\\");
  return WORD;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 472 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-2] = '\0';
  std::string *result = new std::string(yytext);
  result->append("\\");
  yylval.cpp_string = result;
  return WORD;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 480 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-1] = '\0';
  yylval.cpp_string = new std::string(yytext);
  unput('>');
  return WORD;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 487 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-1] = '\0';
  yylval.cpp_string = new std::string(yytext);
  unput('<');
  return WORD;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 494 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-1] = '\0';
  yylval.cpp_string = new std::string(yytext);
  unput('|');
  return WORD;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 501 "shell.l"
{
  int len = strlen(yytext);
  yytext[len-1] = '\0';
  yylval.cpp_string = new std::string(yytext);
  unput('&');
  return WORD;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 508 "shell.l"
{
  yylval.cpp_string = new std::string(yytext + 1, strlen(yytext) - 2);
  return WORD;
}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 512 "shell.l"
{
  fprintf(stderr, "Syntax error: unterminated quoted string\n");
  yyless(0);
  return NOTOKEN;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 517 "shell.l"
{
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 521 "shell.l"
{
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 525 "shell.l"
ECHO;
	YY_BREAK
#line 1710 "lex.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 198 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 198 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 197);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 525 "shell.l"

